### ISSUE TITLE
Tidy text in readme and notebooks

### ISSUE THREAD

**Issue by ElliottKasoar** [Cambridge-ICCS/practical-ml-with-pytorch#30]
Relatively low priority, but when reviewing #29 I noticed that there are a few minor typos in the readme (e.g. "ploting", "neccessary", "sesison", "systems's") that would be nice to clean up during the next pass.

As mentioned in #29, some of text in the exercise/solution notebooks is also a little out of sync.

**Comment by jatkinson1000** [comment]
@dorchard has a PR open to fix some small typos/add additional information - #24 
Could any of this be incorporated there?

**Comment by jatkinson1000** [comment]
This feels stale and I have just created a release post-JOSE review.
I am closing now whilst cleaning.
Feel free to re-open if the issues are still there.
