### ISSUE TITLE
Changes to network achitectures

### ISSUE THREAD

**Issue by jdenholm** [Cambridge-ICCS/practical-ml-with-pytorch#43]
For some reason the non-linear activation functions have been removed from the models in the solutions. This may well work, but it seems very irregular and, since this is for educational purposes, it should be corrected.

**Comment by jatkinson1000** [comment]
Looking at PR #14 they were never there in the first place...?

https://github.com/Cambridge-ICCS/ml-training-material/pull/14

If you can provide the line for the layer I'll append it to the nets in the notebooks.

**Comment by jdenholm** [comment]
There were in the original taught version, but I maybe they never made it into the first version of the worked solutions?

**Comment by jatkinson1000** [comment]
So a ReLU layer at the end of the net in Exercise 1?
